name: Build pc-ble-driver-py
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
env:
  NRF_BLE_DRIVER_VERSION: 4.1.100
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-13, macos-14, windows-2019 ]
        python-version: [ '3.10', '3.11', '3.12' ]
        include:
          - python-version: '3.10'
            toxpy: py310
            macos-python-version: '3.10.9'
          - python-version: '3.11'
            toxpy: py311
            macos-python-version: '3.11.9'
          - python-version: '3.12'
            toxpy: py312
            macos-python-version: '3.12.7'
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: pc-ble-driver-py

    - name: Checkout pc-ble-driver
      uses: actions/checkout@v4
      with:
        repository: embedded-community/pc-ble-driver
        ref: fdbf92831badbca016d2bf95da6fab056ef2d931
        path: pc-ble-driver

    - name: Install linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential libspdlog-dev libasio-dev libudev-dev

    - name: Install macos dependencies
      if: runner.os == 'macOS'
      run: brew install asio spdlog

    - name: Install windows dependencies
      if: runner.os == 'Windows'
      env:
        VCPKG_ROOT: C:\vcpkg
      run: |
        echo "VCPKG_ROOT=${{ env.VCPKG_ROOT }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        vcpkg install --triplet x64-windows asio spdlog

    - name: Setup python
      uses: actions/setup-python@v5
      if: "! contains(matrix.os, 'macos')"
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Setup python for macos
      if: contains(matrix.os, 'macos')
      run: |
        curl -s https://www.python.org/ftp/python/${{ matrix.macos-python-version }}/python-${{ matrix.macos-python-version }}-macos11.pkg --output python.pkg
        sudo installer -pkg python.pkg -target /
        # Find the path of the newly installed Python
        PYTHON_PATH=$(ls /Library/Frameworks/Python.framework/Versions/${{ matrix.python-version }}/bin/python3)
    
        # Create a symbolic link to the installed Python version
        sudo ln -sf $PYTHON_PATH /usr/local/bin/python3
        sudo ln -sf $PYTHON_PATH /usr/local/bin/

        # Prepend /usr/local/bin to PATH to override any default Homebrew paths
        echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV

        PATH=/usr/local/bin:$PATH
        python3 --version
        pip3 install --upgrade pip
        # install explicitly
        pip3 install scikit-build~=0.18.1

    - name: Install Python dependencies
      working-directory: pc-ble-driver-py
      run: python3 -m pip install -r requirements-dev.txt

    - name: Compile pc-ble-driver
      if: runner.os != 'Windows'
      working-directory: pc-ble-driver
      run: |
        mkdir build && cd build
        cmake_args="-DCMAKE_BUILD_TYPE=Release -DDISABLE_TESTS=1 -DNRF_BLE_DRIVER_VERSION=${{ env.NRF_BLE_DRIVER_VERSION }}"
        if [[ "${{ matrix.os }}" == "macos-14" ]]; then
          cmake_args="$cmake_args -DARCH=arm64"
        fi
        cmake $cmake_args -G "Unix Makefiles" ..
        make nrf_ble_driver_sd_api_v5_static
        sudo make install

    - name: Compile pc-ble-driver windows
      if: runner.os == 'Windows'
      working-directory: pc-ble-driver
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DDISABLE_TESTS=1 "-DNRF_BLE_DRIVER_VERSION=${{ env.NRF_BLE_DRIVER_VERSION }}" -G "Visual Studio 16 2019" -A x64 ..
        cmake --build . --config Release
        cmake --install . --config Release

    - name: Build pc-ble-driver-py wheels
      if: runner.os != 'Windows'
      working-directory: pc-ble-driver-py
      run: |
        python3 setup.py bdist_wheel --build-type Release

    - name: Build pc-ble-driver-py wheels windows
      if: runner.os == 'Windows'
      working-directory: pc-ble-driver-py
      run: |
        python3 setup.py bdist_wheel --build-type Release -G "Visual Studio 16 2019" --skip-generator-test

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pc_ble_driver_py-${{ matrix.os }}-${{ matrix.toxpy}}
        path: "pc-ble-driver-py/dist/*.whl"
        if-no-files-found: error

  test:
    name: Verify wheels
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-13, macos-14, windows-2019 ]
        python-version: [ '3.10', '3.11', '3.12' ]
        include:
          - python-version: '3.10'
            toxpy: py310
            macos-python-version: '3.10.9'
          - python-version: '3.11'
            toxpy: py311
            macos-python-version: '3.11.9'
          - python-version: '3.12'
            toxpy: py312
            macos-python-version: '3.12.7'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        if: "! contains(matrix.os, 'macos')"
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Setup python for macos
        if: contains(matrix.os, 'macos')
        run: |
          curl -s https://www.python.org/ftp/python/${{ matrix.macos-python-version }}/python-${{ matrix.macos-python-version }}-macos11.pkg --output python.pkg
          sudo installer -pkg python.pkg -target /
          # Find the path of the newly installed Python
          PYTHON_PATH=$(ls /Library/Frameworks/Python.framework/Versions/${{ matrix.python-version }}/bin/python3)
      
          # Create a symbolic link to the installed Python version
          sudo ln -sf $PYTHON_PATH /usr/local/bin/python3
          sudo ln -sf $PYTHON_PATH /usr/local/bin/
  
          # Prepend /usr/local/bin to PATH to override any default Homebrew paths
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
  
          PATH=/usr/local/bin:$PATH
          python3 --version
          pip3 install --upgrade pip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pc_ble_driver_py-${{ matrix.os }}-${{ matrix.toxpy}}
          path: dist
          
      - name: install wheel
        shell: bash  # this ensure path format works also in windows 
        run: pip3 install dist/*.whl

      # this is sanity check that import works properly. If wheel does not work as expected, this throws
      - name: verify
        run: |
          python3 tests/validate_installation.py
    
  release:
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: upload release assets
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: flatten folder structure
        working-directory: dist
        run: |
          find . -name '*.whl' -exec mv {} . \;
          find . -type d -empty -delete

          # list files
          ls -R

      - name: upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
